version: '3.7'

services:

  api:
    build: ./
    command: pipenv run gunicorn --access-logfile "-" --access-logformat '%(t)s %(p)s %(r)s %(s)s %(b)s' --bind 0.0.0.0:4040 run:app
    ports:
      - 4040:4040
    env_file:
      - ./.env
    environment:
      DB_URL: db # override
      PIPENV_DONT_LOAD_ENV: 1
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER_LOGIN}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}


volumes:
  postgres_data:
