"""Add sandbox reco event

Revision ID: 0cf32c264c4e
Revises: d315fb071f48
Create Date: 2021-02-08 11:26:42.342846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0cf32c264c4e'
down_revision = 'd315fb071f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_launched_for_profile_event',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('occured_at', sa.DateTime(), nullable=False),
                    sa.Column('profile_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['profile_id'], ['profile.profile_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('recommendation_launched_liked_genre',
                    sa.Column('event_id', sa.Integer(), nullable=False),
                    sa.Column('genre_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=45), nullable=True),
                    sa.Column('content_type', postgresql.ENUM('APPLICATION', 'BOOK', 'GAME', 'MOVIE',
                                                              'SERIE', 'TRACK', name='contenttype', create_type=False), nullable=True),
                    sa.ForeignKeyConstraint(['event_id'], [
                        'recommendation_launched_for_profile_event.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('event_id', 'genre_id')
                    )
    op.create_table('recommendation_launched_meta',
                    sa.Column('event_id', sa.Integer(), nullable=False),
                    sa.Column('content_id', sa.Integer(), nullable=False),
                    sa.Column('rating', sa.Integer(), nullable=True),
                    sa.Column('last_rating_date',
                              sa.DateTime(), nullable=True),
                    sa.Column('review_see_count', sa.Integer(), nullable=True),
                    sa.Column('last_review_see_date',
                              sa.DateTime(), nullable=True),
                    sa.Column('count', sa.Integer(), nullable=True),
                    sa.Column('last_count_increment',
                              sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['content_id'], ['content.content_id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['event_id'], [
                        'recommendation_launched_for_profile_event.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('event_id', 'content_id')
                    )
    op.create_table('recommendation_launched_result',
                    sa.Column('event_id', sa.Integer(), nullable=False),
                    sa.Column('content_id', sa.Integer(), nullable=False),
                    sa.Column('score', sa.Float(), nullable=True),
                    sa.Column('engine', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['content_id'], ['content.content_id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['event_id'], [
                        'recommendation_launched_for_profile_event.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('event_id', 'content_id')
                    )
    op.drop_table('bad_recommendation_content_profile')
    op.drop_table('recommended_content_profile')
    op.alter_column('bad_recommendation_content', 'reason',
                    existing_type=sa.TEXT(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bad_recommendation_content', 'reason',
                    existing_type=sa.TEXT(),
                    nullable=True)
    op.create_table('recommended_content_profile',
                    sa.Column('profile_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('content_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('score', postgresql.DOUBLE_PRECISION(
                        precision=53), autoincrement=False, nullable=True),
                    sa.Column('engine', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('engine_priority', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'],
                                            name='recommended_content_profile_content_id_fkey', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'],
                                            name='recommended_content_profile_profile_id_fkey', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('profile_id', 'content_id',
                                            name='recommended_content_profile_pkey')
                    )
    op.create_table('bad_recommendation_content_profile',
                    sa.Column('profile_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('content_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('reason_categorie', sa.TEXT(),
                              autoincrement=False, nullable=False),
                    sa.Column('reason', sa.TEXT(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'],
                                            name='bad_recommendation_content_profile_content_id_fkey', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'],
                                            name='bad_recommendation_content_profile_profile_id_fkey', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('profile_id', 'content_id', 'reason_categorie',
                                            'reason', name='bad_recommendation_content_profile_pkey')
                    )
    op.drop_table('recommendation_launched_result')
    op.drop_table('recommendation_launched_meta')
    op.drop_table('recommendation_launched_liked_genre')
    op.drop_table('recommendation_launched_for_profile_event')
    # ### end Alembic commands ###
