"""Add rating and rating_count for all

Revision ID: 218fc706a3e9
Revises: cfcc46dad572
Create Date: 2020-10-06 14:57:53.463581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218fc706a3e9'
down_revision = 'cfcc46dad572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'reviews',
                    existing_type=sa.VARCHAR(length=45),
                    type_=sa.Integer(),
                    existing_nullable=True,
                    postgresql_using="reviews::integer")
    op.add_column('book', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('book', sa.Column(
        'rating_count', sa.Integer(), nullable=True))
    op.add_column('episode', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('episode', sa.Column(
        'rating_count', sa.Integer(), nullable=True))
    op.alter_column('game', 'recommendations',
                    existing_type=sa.VARCHAR(length=255),
                    type_=sa.Integer(),
                    existing_nullable=True,
                    postgresql_using="recommendations::integer")
    op.add_column('movie', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('movie', sa.Column(
        'rating_count', sa.Integer(), nullable=True))
    op.add_column('serie', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('serie', sa.Column(
        'rating_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serie', 'rating_count')
    op.drop_column('serie', 'rating')
    op.drop_column('movie', 'rating_count')
    op.drop_column('movie', 'rating')
    op.alter_column('game', 'recommendations',
                    existing_type=sa.Integer(),
                    type_=sa.VARCHAR(length=255),
                    existing_nullable=True)
    op.drop_column('episode', 'rating_count')
    op.drop_column('episode', 'rating')
    op.drop_column('book', 'rating_count')
    op.drop_column('book', 'rating')
    op.alter_column('application', 'reviews',
                    existing_type=sa.Integer(),
                    type_=sa.VARCHAR(length=45),
                    existing_nullable=True)
    # ### end Alembic commands ###
