"""Add implicit data for media

Revision ID: 5a638e519d25
Revises: d9479931f85f
Create Date: 2020-10-20 15:30:21.357762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a638e519d25'
down_revision = 'd9479931f85f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meta_user_application', sa.Column(
        'downloaded', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('meta_user_application', sa.Column(
        'review_see_count', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('meta_user_book', sa.Column(
        'purchase', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('meta_user_book', sa.Column('review_see_count',
                                              sa.Integer(), nullable=True, server_default='0'))
    op.add_column('meta_user_game', sa.Column('review_see_count',
                                              sa.Integer(), nullable=True, server_default='0'))
    op.add_column('meta_user_movie', sa.Column('review_see_count',
                                               sa.Integer(), nullable=True, server_default='0'))
    op.add_column('meta_user_movie', sa.Column(
        'watch_count', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('meta_user_serie', sa.Column(
        'num_watched_episodes', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('meta_user_serie', sa.Column('review_see_count',
                                               sa.Integer(), nullable=True, server_default='0'))
    op.add_column('meta_user_track', sa.Column(
        'play_count', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('meta_user_track', sa.Column('review_see_count',
                                               sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meta_user_track', 'review_see_count')
    op.drop_column('meta_user_track', 'play_count')
    op.drop_column('meta_user_serie', 'review_see_count')
    op.drop_column('meta_user_serie', 'num_watched_episodes')
    op.drop_column('meta_user_movie', 'watch_count')
    op.drop_column('meta_user_movie', 'review_see_count')
    op.drop_column('meta_user_game', 'review_see_count')
    op.drop_column('meta_user_book', 'review_see_count')
    op.drop_column('meta_user_book', 'purchase')
    op.drop_column('meta_user_application', 'review_see_count')
    op.drop_column('meta_user_application', 'downloaded')
    # ### end Alembic commands ###
