"""recommendation for a group

Revision ID: 6009b9b7578e
Revises: a533d6b2f5fb
Create Date: 2020-11-14 20:58:14.959597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6009b9b7578e'
down_revision = 'a533d6b2f5fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommended_application_for_group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('engine_priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['application.app_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['group.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'app_id')
    )
    op.create_table('recommended_book_for_group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('engine_priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['isbn'], ['book.isbn'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'isbn')
    )
    op.create_table('recommended_game_for_group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('engine_priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['group.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'game_id')
    )
    op.create_table('recommended_movie_for_group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('engine_priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.movie_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'movie_id')
    )
    op.create_table('recommended_serie_for_group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('engine_priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['serie_id'], ['serie.serie_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'serie_id')
    )
    op.create_table('recommended_track_for_group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('engine_priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['track.track_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'track_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommended_track_for_group')
    op.drop_table('recommended_serie_for_group')
    op.drop_table('recommended_movie_for_group')
    op.drop_table('recommended_game_for_group')
    op.drop_table('recommended_book_for_group')
    op.drop_table('recommended_application_for_group')
    # ### end Alembic commands ###
