"""Concat all content type genres in one table

Revision ID: 66b006a04b7b
Revises: a5e9878c602c
Create Date: 2020-10-14 22:18:03.216152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b006a04b7b'
down_revision = 'a5e9878c602c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('genre_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.Enum('APPLICATION', 'BOOK', 'GAME', 'MOVIE', 'SERIE', 'TRACK', name='contenttype'), nullable=True),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_table('liked_genres',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'genre_id')
    )
    op.create_table('linked_genre',
    sa.Column('genre_id0', sa.Integer(), nullable=False),
    sa.Column('genre_id1', sa.Integer(), nullable=False),
    sa.Column('ratio', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id0'], ['genre.genre_id'], ),
    sa.ForeignKeyConstraint(['genre_id1'], ['genre.genre_id'], ),
    sa.PrimaryKeyConstraint('genre_id0', 'genre_id1')
    )
    op.drop_index('ix_s_track_genres_genre', table_name='s_track_genres')
    op.drop_table('s_track_genres')
    op.drop_index('ix_s_game_genres_genre', table_name='s_game_genres')
    op.drop_table('s_game_genres')
    op.drop_index('ix_s_application_categories_category', table_name='s_application_categories')
    op.drop_table('s_application_categories')
    op.drop_index('ix_s_movie_genres_genre', table_name='s_movie_genres')
    op.drop_table('s_movie_genres')
    op.drop_index('ix_s_serie_genres_genre', table_name='s_serie_genres')
    op.drop_table('s_serie_genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s_serie_genres',
    sa.Column('genre', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('genre', name='s_serie_genres_pkey')
    )
    op.create_index('ix_s_serie_genres_genre', 's_serie_genres', ['genre'], unique=False)
    op.create_table('s_movie_genres',
    sa.Column('genre', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('genre', name='s_movie_genres_pkey')
    )
    op.create_index('ix_s_movie_genres_genre', 's_movie_genres', ['genre'], unique=False)
    op.create_table('s_application_categories',
    sa.Column('category', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('category', name='s_application_categories_pkey')
    )
    op.create_index('ix_s_application_categories_category', 's_application_categories', ['category'], unique=False)
    op.create_table('s_game_genres',
    sa.Column('genre', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('genre', name='s_game_genres_pkey')
    )
    op.create_index('ix_s_game_genres_genre', 's_game_genres', ['genre'], unique=False)
    op.create_table('s_track_genres',
    sa.Column('genre', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('genre', name='s_track_genres_pkey')
    )
    op.create_index('ix_s_track_genres_genre', 's_track_genres', ['genre'], unique=False)
    op.drop_table('linked_genre')
    op.drop_table('liked_genres')
    op.drop_table('genre')
    # ### end Alembic commands ###
