"""fix user deletion cascade

Revision ID: 6f2981ad367c
Revises: 8e860798bd13
Create Date: 2020-11-06 15:21:38.791098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f2981ad367c'
down_revision = '8e860798bd13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('group_owner_id_fkey', 'group', type_='foreignkey')
    op.create_foreign_key(None, 'group', 'user', ['owner_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('group_members_group_id_fkey', 'group_members', type_='foreignkey')
    op.drop_constraint('group_members_user_id_fkey', 'group_members', type_='foreignkey')
    op.create_foreign_key(None, 'group_members', 'group', ['group_id'], ['group_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'group_members', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('invitations_group_id_fkey', 'invitations', type_='foreignkey')
    op.drop_constraint('invitations_user_id_fkey', 'invitations', type_='foreignkey')
    op.create_foreign_key(None, 'invitations', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'invitations', 'group', ['group_id'], ['group_id'], ondelete='CASCADE')
    op.drop_constraint('liked_genres_user_id_fkey', 'liked_genres', type_='foreignkey')
    op.drop_constraint('liked_genres_genre_id_fkey', 'liked_genres', type_='foreignkey')
    op.create_foreign_key(None, 'liked_genres', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'liked_genres', 'genre', ['genre_id'], ['genre_id'], ondelete='CASCADE')
    op.drop_constraint('meta_user_application_user_id_fkey', 'meta_user_application', type_='foreignkey')
    op.drop_constraint('meta_user_application_app_id_fkey', 'meta_user_application', type_='foreignkey')
    op.create_foreign_key(None, 'meta_user_application', 'application', ['app_id'], ['app_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'meta_user_application', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('meta_user_book_isbn_fkey', 'meta_user_book', type_='foreignkey')
    op.drop_constraint('meta_user_book_user_id_fkey', 'meta_user_book', type_='foreignkey')
    op.create_foreign_key(None, 'meta_user_book', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'meta_user_book', 'book', ['isbn'], ['isbn'], ondelete='CASCADE')
    op.drop_constraint('meta_user_game_user_id_fkey', 'meta_user_game', type_='foreignkey')
    op.drop_constraint('meta_user_game_game_id_fkey', 'meta_user_game', type_='foreignkey')
    op.create_foreign_key(None, 'meta_user_game', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'meta_user_game', 'game', ['game_id'], ['game_id'], ondelete='CASCADE')
    op.drop_constraint('meta_user_movie_movie_id_fkey', 'meta_user_movie', type_='foreignkey')
    op.drop_constraint('meta_user_movie_user_id_fkey', 'meta_user_movie', type_='foreignkey')
    op.create_foreign_key(None, 'meta_user_movie', 'movie', ['movie_id'], ['movie_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'meta_user_movie', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('meta_user_serie_serie_id_fkey', 'meta_user_serie', type_='foreignkey')
    op.drop_constraint('meta_user_serie_user_id_fkey', 'meta_user_serie', type_='foreignkey')
    op.create_foreign_key(None, 'meta_user_serie', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'meta_user_serie', 'serie', ['serie_id'], ['serie_id'], ondelete='CASCADE')
    op.drop_constraint('meta_user_track_user_id_fkey', 'meta_user_track', type_='foreignkey')
    op.drop_constraint('meta_user_track_track_id_fkey', 'meta_user_track', type_='foreignkey')
    op.create_foreign_key(None, 'meta_user_track', 'track', ['track_id'], ['track_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'meta_user_track', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meta_user_track', type_='foreignkey')
    op.drop_constraint(None, 'meta_user_track', type_='foreignkey')
    op.create_foreign_key('meta_user_track_track_id_fkey', 'meta_user_track', 'track', ['track_id'], ['track_id'])
    op.create_foreign_key('meta_user_track_user_id_fkey', 'meta_user_track', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'meta_user_serie', type_='foreignkey')
    op.drop_constraint(None, 'meta_user_serie', type_='foreignkey')
    op.create_foreign_key('meta_user_serie_user_id_fkey', 'meta_user_serie', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key('meta_user_serie_serie_id_fkey', 'meta_user_serie', 'serie', ['serie_id'], ['serie_id'])
    op.drop_constraint(None, 'meta_user_movie', type_='foreignkey')
    op.drop_constraint(None, 'meta_user_movie', type_='foreignkey')
    op.create_foreign_key('meta_user_movie_user_id_fkey', 'meta_user_movie', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key('meta_user_movie_movie_id_fkey', 'meta_user_movie', 'movie', ['movie_id'], ['movie_id'])
    op.drop_constraint(None, 'meta_user_game', type_='foreignkey')
    op.drop_constraint(None, 'meta_user_game', type_='foreignkey')
    op.create_foreign_key('meta_user_game_game_id_fkey', 'meta_user_game', 'game', ['game_id'], ['game_id'])
    op.create_foreign_key('meta_user_game_user_id_fkey', 'meta_user_game', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'meta_user_book', type_='foreignkey')
    op.drop_constraint(None, 'meta_user_book', type_='foreignkey')
    op.create_foreign_key('meta_user_book_user_id_fkey', 'meta_user_book', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key('meta_user_book_isbn_fkey', 'meta_user_book', 'book', ['isbn'], ['isbn'])
    op.drop_constraint(None, 'meta_user_application', type_='foreignkey')
    op.drop_constraint(None, 'meta_user_application', type_='foreignkey')
    op.create_foreign_key('meta_user_application_app_id_fkey', 'meta_user_application', 'application', ['app_id'], ['app_id'])
    op.create_foreign_key('meta_user_application_user_id_fkey', 'meta_user_application', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'liked_genres', type_='foreignkey')
    op.drop_constraint(None, 'liked_genres', type_='foreignkey')
    op.create_foreign_key('liked_genres_genre_id_fkey', 'liked_genres', 'genre', ['genre_id'], ['genre_id'])
    op.create_foreign_key('liked_genres_user_id_fkey', 'liked_genres', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.create_foreign_key('invitations_user_id_fkey', 'invitations', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key('invitations_group_id_fkey', 'invitations', 'group', ['group_id'], ['group_id'])
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_foreign_key('group_members_user_id_fkey', 'group_members', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key('group_members_group_id_fkey', 'group_members', 'group', ['group_id'], ['group_id'])
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.create_foreign_key('group_owner_id_fkey', 'group', 'user', ['owner_id'], ['user_id'])
    # ### end Alembic commands ###
