"""Add rating to Game media

Revision ID: 7de2196cb792
Revises: 5a638e519d25
Create Date: 2020-10-21 00:21:08.343844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de2196cb792'
down_revision = '5a638e519d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('game', sa.Column('rating_count', sa.Integer(),
                                    nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'rating_count')
    op.drop_column('game', 'rating')
    # ### end Alembic commands ###
