"""Add additional media tables

Revision ID: 83a8d40676c4
Revises: aafc7a8cca46
Create Date: 2021-01-28 18:58:40.915304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '83a8d40676c4'
down_revision = 'aafc7a8cca46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_additional',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('size', sa.String(length=255), nullable=True),
    sa.Column('installs', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=45), nullable=True),
    sa.Column('price', sa.String(length=45), nullable=True),
    sa.Column('content_rating', sa.String(length=255), nullable=True),
    sa.Column('last_updated', sa.String(length=255), nullable=True),
    sa.Column('current_version', sa.String(length=255), nullable=True),
    sa.Column('android_version', sa.String(length=255), nullable=True),
    sa.Column('cover', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('app_id')
    )
    op.create_index(op.f('ix_application_additional_app_id'), 'application_additional', ['app_id'], unique=False)
    op.create_index(op.f('ix_application_additional_name'), 'application_additional', ['name'], unique=True)
    op.create_table('book_additional',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('year_of_publication', sa.Integer(), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('image_url_s', sa.Text(), nullable=True),
    sa.Column('image_url_m', sa.Text(), nullable=True),
    sa.Column('image_url_l', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index(op.f('ix_book_additional_author'), 'book_additional', ['author'], unique=False)
    op.create_index(op.f('ix_book_additional_book_id'), 'book_additional', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_additional_isbn'), 'book_additional', ['isbn'], unique=True)
    op.create_index(op.f('ix_book_additional_title'), 'book_additional', ['title'], unique=False)
    op.create_table('game_additional',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('steamid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('header_image', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('developers', sa.String(length=255), nullable=True),
    sa.Column('publishers', sa.String(length=255), nullable=True),
    sa.Column('price', sa.String(length=255), nullable=True),
    sa.Column('release_date', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index(op.f('ix_game_additional_game_id'), 'game_additional', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_additional_name'), 'game_additional', ['name'], unique=False)
    op.create_table('movie_additional',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=255), nullable=True),
    sa.Column('actors', sa.Text(), nullable=True),
    sa.Column('year', sa.String(length=255), nullable=True),
    sa.Column('producers', sa.Text(), nullable=True),
    sa.Column('director', sa.Text(), nullable=True),
    sa.Column('writer', sa.Text(), nullable=True),
    sa.Column('imdbid', sa.String(length=255), nullable=True),
    sa.Column('tmdbid', sa.String(length=255), nullable=True),
    sa.Column('cover', sa.Text(), nullable=True),
    sa.Column('plot_outline', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_index(op.f('ix_movie_additional_movie_id'), 'movie_additional', ['movie_id'], unique=False)
    op.create_index(op.f('ix_movie_additional_title'), 'movie_additional', ['title'], unique=False)
    op.create_table('serie_additional',
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('imdbid', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('writers', sa.Text(), nullable=True),
    sa.Column('directors', sa.Text(), nullable=True),
    sa.Column('actors', sa.Text(), nullable=True),
    sa.Column('cover', sa.Text(), nullable=True),
    sa.Column('plot_outline', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('serie_id')
    )
    op.create_index(op.f('ix_serie_additional_serie_id'), 'serie_additional', ['serie_id'], unique=False)
    op.create_index(op.f('ix_serie_additional_title'), 'serie_additional', ['title'], unique=False)
    op.create_table('track_additional',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('artist_name', sa.String(length=255), nullable=True),
    sa.Column('release', sa.String(length=255), nullable=True),
    sa.Column('track_mmid', sa.String(length=45), nullable=True),
    sa.Column('recording_mbid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('spotify_id', sa.String(length=45), nullable=True),
    sa.Column('covert_art_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('track_id')
    )
    op.create_index(op.f('ix_track_additional_artist_name'), 'track_additional', ['artist_name'], unique=False)
    op.create_index(op.f('ix_track_additional_title'), 'track_additional', ['title'], unique=False)
    op.create_index(op.f('ix_track_additional_track_id'), 'track_additional', ['track_id'], unique=False)
    op.create_table('application_additional_genres',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['application_additional.app_id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ),
    sa.PrimaryKeyConstraint('app_id', 'genre_id')
    )
    op.create_table('episode_additional',
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('imdbid', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('serie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['serie_id'], ['serie_additional.serie_id'], ),
    sa.PrimaryKeyConstraint('episode_id')
    )
    op.create_index(op.f('ix_episode_additional_episode_id'), 'episode_additional', ['episode_id'], unique=False)
    op.create_index(op.f('ix_episode_additional_title'), 'episode_additional', ['title'], unique=False)
    op.create_table('game_additional_genres',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game_additional.game_id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'genre_id')
    )
    op.create_table('movie_additional_genres',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie_additional.movie_id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    op.create_table('serie_additional_genres',
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ),
    sa.ForeignKeyConstraint(['serie_id'], ['serie_additional.serie_id'], ),
    sa.PrimaryKeyConstraint('serie_id', 'genre_id')
    )
    op.create_table('track_additional_genres',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track_additional.track_id'], ),
    sa.PrimaryKeyConstraint('track_id', 'genre_id')
    )
    op.create_table('episode_additional_genres',
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episode_additional.episode_id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ),
    sa.PrimaryKeyConstraint('episode_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episode_additional_genres')
    op.drop_table('track_additional_genres')
    op.drop_table('serie_additional_genres')
    op.drop_table('movie_additional_genres')
    op.drop_table('game_additional_genres')
    op.drop_index(op.f('ix_episode_additional_title'), table_name='episode_additional')
    op.drop_index(op.f('ix_episode_additional_episode_id'), table_name='episode_additional')
    op.drop_table('episode_additional')
    op.drop_table('application_additional_genres')
    op.drop_index(op.f('ix_track_additional_track_id'), table_name='track_additional')
    op.drop_index(op.f('ix_track_additional_title'), table_name='track_additional')
    op.drop_index(op.f('ix_track_additional_artist_name'), table_name='track_additional')
    op.drop_table('track_additional')
    op.drop_index(op.f('ix_serie_additional_title'), table_name='serie_additional')
    op.drop_index(op.f('ix_serie_additional_serie_id'), table_name='serie_additional')
    op.drop_table('serie_additional')
    op.drop_index(op.f('ix_movie_additional_title'), table_name='movie_additional')
    op.drop_index(op.f('ix_movie_additional_movie_id'), table_name='movie_additional')
    op.drop_table('movie_additional')
    op.drop_index(op.f('ix_game_additional_name'), table_name='game_additional')
    op.drop_index(op.f('ix_game_additional_game_id'), table_name='game_additional')
    op.drop_table('game_additional')
    op.drop_index(op.f('ix_book_additional_title'), table_name='book_additional')
    op.drop_index(op.f('ix_book_additional_isbn'), table_name='book_additional')
    op.drop_index(op.f('ix_book_additional_book_id'), table_name='book_additional')
    op.drop_index(op.f('ix_book_additional_author'), table_name='book_additional')
    op.drop_table('book_additional')
    op.drop_index(op.f('ix_application_additional_name'), table_name='application_additional')
    op.drop_index(op.f('ix_application_additional_app_id'), table_name='application_additional')
    op.drop_table('application_additional')
    # ### end Alembic commands ###
