"""Add popularity_score to media

Revision ID: 8af6bbfba52a
Revises: d14fb14bfba2
Create Date: 2020-11-01 16:05:47.665538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af6bbfba52a'
down_revision = 'd14fb14bfba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('popularity_score', sa.Float(), nullable=True, server_default='0'))
    op.add_column('book', sa.Column('popularity_score', sa.Float(), nullable=True, server_default='0'))
    op.add_column('game', sa.Column('popularity_score', sa.Float(), nullable=True, server_default='0'))
    op.add_column('movie', sa.Column('popularity_score', sa.Float(), nullable=True, server_default='0'))
    op.add_column('serie', sa.Column('popularity_score', sa.Float(), nullable=True, server_default='0'))
    op.add_column('track', sa.Column('popularity_score', sa.Float(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'popularity_score')
    op.drop_column('serie', 'popularity_score')
    op.drop_column('movie', 'popularity_score')
    op.drop_column('game', 'popularity_score')
    op.drop_column('book', 'popularity_score')
    op.drop_column('application', 'popularity_score')
    # ### end Alembic commands ###
