"""add recommended media tables

Revision ID: 9d02e3650941
Revises: 6f2981ad367c
Create Date: 2020-11-11 21:43:00.109495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d02e3650941'
down_revision = '6f2981ad367c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recomended_book',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['book.isbn'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'isbn')
    )
    op.create_table('recomended_game',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'game_id')
    )
    op.create_table('recomended_movie',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.movie_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'movie_id')
    )
    op.create_table('recomended_serie',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['serie_id'], ['serie.serie_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'serie_id')
    )
    op.create_table('recomended_track',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['track.track_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'track_id')
    )
    op.create_table('recomended_application',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['application.app_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'app_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recomended_application')
    op.drop_table('recomended_track')
    op.drop_table('recomended_serie')
    op.drop_table('recomended_movie')
    op.drop_table('recomended_game')
    op.drop_table('recomended_book')
    # ### end Alembic commands ###
