"""cascade_delete_external_serv

Revision ID: a533d6b2f5fb
Revises: da986121e60f
Create Date: 2020-11-14 20:51:11.111952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a533d6b2f5fb'
down_revision = 'da986121e60f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('external_service_user_id_fkey', 'external_service', type_='foreignkey')
    op.create_foreign_key(None, 'external_service', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'external_service', type_='foreignkey')
    op.create_foreign_key('external_service_user_id_fkey', 'external_service', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
