"""add genres and categories

Revision ID: a5e9878c602c
Revises: cfe8f681c7b7
Create Date: 2020-10-14 00:04:59.724396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e9878c602c'
down_revision = 'cfe8f681c7b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s_application_categories',
    sa.Column('category', sa.String(length=45), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('category')
    )
    op.create_index(op.f('ix_s_application_categories_category'), 's_application_categories', ['category'], unique=False)
    op.create_table('s_game_genres',
    sa.Column('genre', sa.String(length=45), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('genre')
    )
    op.create_index(op.f('ix_s_game_genres_genre'), 's_game_genres', ['genre'], unique=False)
    op.create_table('s_movie_genres',
    sa.Column('genre', sa.String(length=45), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('genre')
    )
    op.create_index(op.f('ix_s_movie_genres_genre'), 's_movie_genres', ['genre'], unique=False)
    op.create_table('s_serie_genres',
    sa.Column('genre', sa.String(length=45), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('genre')
    )
    op.create_index(op.f('ix_s_serie_genres_genre'), 's_serie_genres', ['genre'], unique=False)
    op.create_table('s_track_genres',
    sa.Column('genre', sa.String(length=45), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('genre')
    )
    op.create_index(op.f('ix_s_track_genres_genre'), 's_track_genres', ['genre'], unique=False)
    op.add_column('movie', sa.Column('cover', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'cover')
    op.drop_index(op.f('ix_s_track_genres_genre'), table_name='s_track_genres')
    op.drop_table('s_track_genres')
    op.drop_index(op.f('ix_s_serie_genres_genre'), table_name='s_serie_genres')
    op.drop_table('s_serie_genres')
    op.drop_index(op.f('ix_s_movie_genres_genre'), table_name='s_movie_genres')
    op.drop_table('s_movie_genres')
    op.drop_index(op.f('ix_s_game_genres_genre'), table_name='s_game_genres')
    op.drop_table('s_game_genres')
    op.drop_index(op.f('ix_s_application_categories_category'), table_name='s_application_categories')
    op.drop_table('s_application_categories')
    # ### end Alembic commands ###
