"""Add recovery password fields in user model

Revision ID: b7c2dc62629d
Revises: eec96839d197
Create Date: 2020-10-22 15:00:41.751397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c2dc62629d'
down_revision = 'eec96839d197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'reset_password_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reset_password_token')
    # ### end Alembic commands ###
