"""Add serie and episode tables

Revision ID: cfcc46dad572
Revises: a29c28d42cd8
Create Date: 2020-10-05 17:30:57.475712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfcc46dad572'
down_revision = 'a29c28d42cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serie',
    sa.Column('serie_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('imdbid', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('writers', sa.Text(), nullable=True),
    sa.Column('directors', sa.Text(), nullable=True),
    sa.Column('actors', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('serie_id')
    )
    op.create_index(op.f('ix_serie_serie_id'), 'serie', ['serie_id'], unique=False)
    op.create_index(op.f('ix_serie_title'), 'serie', ['title'], unique=False)
    op.create_table('episode',
    sa.Column('episode_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('imdbid', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('serie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['serie_id'], ['serie.serie_id'], ),
    sa.PrimaryKeyConstraint('episode_id')
    )
    op.create_index(op.f('ix_episode_episode_id'), 'episode', ['episode_id'], unique=False)
    op.create_index(op.f('ix_episode_title'), 'episode', ['title'], unique=False)
    op.create_table('meta_user_serie',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['serie_id'], ['serie.serie_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'serie_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meta_user_serie')
    op.drop_index(op.f('ix_episode_title'), table_name='episode')
    op.drop_index(op.f('ix_episode_episode_id'), table_name='episode')
    op.drop_table('episode')
    op.drop_index(op.f('ix_serie_title'), table_name='serie')
    op.drop_index(op.f('ix_serie_serie_id'), table_name='serie')
    op.drop_table('serie')
    # ### end Alembic commands ###
