"""Add serie and app cover

Revision ID: d14fb14bfba2
Revises: eec96839d197
Create Date: 2020-10-27 09:16:26.141028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd14fb14bfba2'
down_revision = 'eec96839d197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('cover', sa.Text(), nullable=True))
    op.add_column('serie', sa.Column('cover', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serie', 'cover')
    op.drop_column('application', 'cover')
    # ### end Alembic commands ###
