"""change profile.uuid_user to profile.user_id

Revision ID: d315fb071f48
Revises: 61c456ca257e
Create Date: 2021-01-28 22:30:48.437078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'd315fb071f48'
down_revision = '61c456ca257e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
                    sa.Column('profile_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('uuid', postgresql.UUID(
                        as_uuid=True), nullable=True),
                    sa.Column('profilename', sa.String(
                        length=45), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['user.user_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('profile_id'),
                    sa.UniqueConstraint('uuid')
                    )
    op.create_index(op.f('ix_profile_profile_id'),
                    'profile', ['profile_id'], unique=False)
    op.create_table('bad_recommendation_content_profile',
                    sa.Column('profile_id', sa.Integer(), nullable=False),
                    sa.Column('content_id', sa.Integer(), nullable=False),
                    sa.Column('reason_categorie', sa.Text(), nullable=False),
                    sa.Column('reason', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['content_id'], ['content.content_id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['profile_id'], ['profile.profile_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint(
                        'profile_id', 'content_id', 'reason_categorie', 'reason')
                    )
    op.create_table('liked_genres_profile',
                    sa.Column('profile_id', sa.Integer(), nullable=False),
                    sa.Column('genre_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['genre_id'], ['genre.genre_id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['profile_id'], ['profile.profile_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('profile_id', 'genre_id')
                    )
    op.create_table('meta_profile_content',
                    sa.Column('profile_id', sa.Integer(), nullable=False),
                    sa.Column('content_id', sa.Integer(), nullable=False),
                    sa.Column('rating', sa.Integer(), nullable=True),
                    sa.Column('last_rating_date',
                              sa.DateTime(), nullable=True),
                    sa.Column('review_see_count', sa.Integer(), nullable=True),
                    sa.Column('last_review_see_date',
                              sa.DateTime(), nullable=True),
                    sa.Column('count', sa.Integer(), nullable=True),
                    sa.Column('last_count_increment',
                              sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['content_id'], ['content.content_id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['profile_id'], ['profile.profile_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('profile_id', 'content_id')
                    )
    op.create_table('recommended_content_profile',
                    sa.Column('profile_id', sa.Integer(), nullable=False),
                    sa.Column('content_id', sa.Integer(), nullable=False),
                    sa.Column('score', sa.Float(), nullable=True),
                    sa.Column('engine', sa.String(), nullable=True),
                    sa.Column('engine_priority', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['content_id'], ['content.content_id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['profile_id'], ['profile.profile_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('profile_id', 'content_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommended_content_profile')
    op.drop_table('meta_profile_content')
    op.drop_table('liked_genres_profile')
    op.drop_table('bad_recommendation_content_profile')
    op.drop_index(op.f('ix_profile_profile_id'), table_name='profile')
    op.drop_table('profile')
    # ### end Alembic commands ###
