"""Link serie movie game to genre

Revision ID: d9479931f85f
Revises: ab15fc5202bb
Create Date: 2020-10-17 12:55:54.926143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9479931f85f'
down_revision = 'ab15fc5202bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_genres',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'genre_id')
    )
    op.create_table('movie_genres',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.movie_id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    op.create_table('serie_genres',
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ),
    sa.ForeignKeyConstraint(['serie_id'], ['serie.serie_id'], ),
    sa.PrimaryKeyConstraint('serie_id', 'genre_id')
    )
    op.drop_column('application', 'genres')
    op.drop_column('game', 'genres')
    op.drop_column('movie', 'genres')
    op.drop_column('serie', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serie', sa.Column('genres', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('movie', sa.Column('genres', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('genres', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('application', sa.Column('genres', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('serie_genres')
    op.drop_table('movie_genres')
    op.drop_table('game_genres')
    # ### end Alembic commands ###
