"""add date for count for meta and delete useless episode cols

Revision ID: e77266cebfe9
Revises: de549af9a501
Create Date: 2021-01-07 16:10:30.915070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e77266cebfe9'
down_revision = 'de549af9a501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode', 'rating')
    op.drop_column('episode', 'genres')
    op.drop_column('episode', 'rating_count')
    op.add_column('meta_user_content', sa.Column('last_count_increment', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meta_user_content', 'last_count_increment')
    op.add_column('episode', sa.Column('rating_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('episode', sa.Column('genres', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('episode', sa.Column('rating', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
