"""delete play_count on meta_user_track

Revision ID: eb2db2d0a336
Revises: 7f94a96df15e
Create Date: 2020-09-29 23:25:07.953003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2db2d0a336'
down_revision = '7f94a96df15e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meta_user_track', 'play_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meta_user_track', sa.Column('play_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
