"""delete track language

Revision ID: ebfe49179def
Revises: 66b006a04b7b
Create Date: 2020-10-14 23:27:29.300073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebfe49179def'
down_revision = '66b006a04b7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('language', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
