"""Add engine table to known last launch time

Revision ID: eecf1702bc5c
Revises: 0cf32c264c4e
Create Date: 2021-02-14 18:41:38.842449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eecf1702bc5c'
down_revision = '0cf32c264c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine',
    sa.Column('engine', sa.String(), nullable=False),
    sa.Column('last_launch_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('engine')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('engine')
    # ### end Alembic commands ###
