"""Add implicit data for media

Revision ID: f27839a3a7f8
Revises: d9479931f85f
Create Date: 2020-10-19 19:23:55.313672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27839a3a7f8'
down_revision = 'd9479931f85f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meta_user_book', sa.Column('purchase', sa.Boolean(), nullable=True))
    op.add_column('meta_user_movie', sa.Column('watch_count', sa.Integer(), nullable=True))
    op.add_column('meta_user_serie', sa.Column('num_watched_episodes', sa.Integer(), nullable=True))
    op.add_column('meta_user_track', sa.Column('play_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meta_user_track', 'play_count')
    op.drop_column('meta_user_serie', 'num_watched_episodes')
    op.drop_column('meta_user_movie', 'watch_count')
    op.drop_column('meta_user_book', 'purchase')
    # ### end Alembic commands ###
