"""add external service table

Revision ID: f2964286631a
Revises: d14fb14bfba2
Create Date: 2020-11-05 14:50:49.790384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2964286631a'
down_revision = 'd14fb14bfba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_service',
    sa.Column('service_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=45), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('service_id'),
    sa.UniqueConstraint('user_id', 'service_name', name='unique_userID_serviceName')
    )
    op.create_index(op.f('ix_external_service_service_id'), 'external_service', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_service_service_id'), table_name='external_service')
    op.drop_table('external_service')
    # ### end Alembic commands ###
