"""add external service table

Revision ID: f392e7ff7895
Revises: 6a93a854077f
Create Date: 2020-11-01 12:47:31.826373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f392e7ff7895'
down_revision = '6a93a854077f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_service',
    sa.Column('service_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=45), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_index(op.f('ix_external_service_service_id'), 'external_service', ['service_id'], unique=False)
    op.drop_column('user', 'reset_password_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reset_password_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_external_service_service_id'), table_name='external_service')
    op.drop_table('external_service')
    # ### end Alembic commands ###
