name: Test and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          make init
          sudo apt install libxml2-utils

      - name: Test with pytest
        run: make test

      - name: Coverage badge
        if: ${{ always() }}
        run: pipenv run anybadge -l coverage -v $(xmllint --html --xpath "//div[@id='header']/div/h1/span/text()" build/coverage/index.html) -f build/coverage.svg

      - name: Tests status badge
        if: ${{ success() }}
        run: pipenv run anybadge -l tests -v passing -f build/tests.svg passing=green failing=red

      - name: Tests status badge
        if: ${{ failure() }}
        run: pipenv run anybadge -l tests -v failing -f build/tests.svg passing=green failing=red

      - name: Deploy
        if: ${{ always() }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
