name: Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install Python dependencies
        run: |
          python -m pip install sqlite-utils
          sqlite-utils --version
          sqlite --version

      - name: Install dependencies
        run: make init

      - name: Test with pytest
        run: make test
