name: Test and Deploy

on: [push]
  # push:
  #   branches:
  #     - master
  # pull_request:
  #   branches:
  #     - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          make init
          sudo apt install libxml2

      - name: Test with pytest
        run: make test

      - name: Badge
        run: |
          score = $(xmllint --html --xpath "span[@id='pc_cov']" build/coverage/index.html)
          pipenv run anybadge -v $score -f build/coverage.svg coverage
          pipenv run anybadge -v passing -f build/tests.svg tests

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
